#!/bin/sh
#SBATCH --partition=epyc
#SBATCH --time=1-00:00
#SBATCH --ntasks=1
#SBATCH --mem=2G
#SBATCH --cpus-per-task=48
#SBATCH --job-name=reg_features_predict
#SBATCH --error=%x-%A_%a.out
#SBATCH --output=%x-%A_%a.out
#SBATCH --array=0-3

SLURM_ARRAY_TASK_ID=${SLURM_ARRAY_TASK_ID:-1}  # Default to 1 if not set

SCRIPT=../../../bin/gkmpredict
FASTA="./FASTAs/combined_test.fa"
MODEL="./enhancer_vs_promoter_vs_CTCF.t3.model.txt"
KMERS=./FASTAs/kmers_11.fa

commands=(
 "$SCRIPT -t $SLURM_CPUS_PER_TASK -D $FASTA $MODEL ./predictions_D/combined_test_scores.txt"
 "$SCRIPT -t $SLURM_CPUS_PER_TASK -P $FASTA $MODEL ./predictions_P/combined_test_scores.txt"
 "$SCRIPT -t $SLURM_CPUS_PER_TASK -D $KMERS $MODEL ./motifs_D/kmers_11_scores.txt"
 "$SCRIPT -t $SLURM_CPUS_PER_TASK -P $KMERS $MODEL ./motifs_P/kmers_11_scores.txt"
)

make_dir_commands=(
 "mkdir -p ./predictions_D"
 "mkdir -p ./predictions_P"
 "mkdir -p ./motifs_D"
 "mkdir -p ./motifs_P"
)

echo "Running command: ${commands[$SLURM_ARRAY_TASK_ID]}"
${make_dir_commands[$SLURM_ARRAY_TASK_ID]}
${commands[$SLURM_ARRAY_TASK_ID]}
