name: mLS-GKM
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # --- defaults ---
  - defaults::_tflow_select=2.3.0
  - defaults::astroid=2.14.2
  - defaults::dbus=1.16.2
  - defaults::grpc-cpp=1.39.0
  - defaults::gst-plugins-base=1.14.1
  - defaults::gstreamer=1.14.1
  - defaults::hdf5=1.10.6
  - defaults::libpq=12.20
  - defaults::libxml2=2.9.14
  - defaults::libxslt=1.1.35
  - defaults::pillow=8.3.1
  - defaults::pydocstyle=6.3.0
  - defaults::qt-main=5.15.2
  - defaults::scipy=1.7.3
  - defaults::tensorflow=1.15.0
  - defaults::tensorflow-base=1.15.0
  - defaults::tensorflow-estimator=1.15.1
  # --- conda-forge ---
  - conda-forge::_libgcc_mutex=0.1
  - conda-forge::_openmp_mutex=4.5
  - conda-forge::abseil-cpp=20200923.3
  - conda-forge::absl-py=0.15.0
  - conda-forge::aiofiles=22.1.0
  - conda-forge::aiohttp=3.7.4.post0
  - conda-forge::aiosqlite=0.20.0
  - conda-forge::alsa-lib=1.2.7.2
  - conda-forge::anyio=3.7.1
  - conda-forge::argon2-cffi=23.1.0
  - conda-forge::argon2-cffi-bindings=21.2.0
  - conda-forge::arrow=1.2.3
  - conda-forge::astor=0.8.1
  - conda-forge::astunparse=1.6.3
  - conda-forge::async-timeout=3.0.1
  - conda-forge::attr=2.5.2
  - conda-forge::attrs=24.2.0
  - conda-forge::autopep8=2.0.2
  - conda-forge::babel=2.14.0
  - conda-forge::backcall=0.2.0
  - conda-forge::backports=1.0
  - conda-forge::backports.functools_lru_cache=2.0.0
  - conda-forge::beautifulsoup4=4.12.3
  - conda-forge::binutils_impl_linux-64=2.45.1
  - conda-forge::binutils_linux-64=2.45.1
  - conda-forge::biopython=1.79
  - conda-forge::blas=2.305
  - conda-forge::blas-devel=3.11.0
  - conda-forge::bleach=6.1.0
  - conda-forge::blinker=1.6.3
  - conda-forge::brotli=1.2.0
  - conda-forge::brotli-bin=1.2.0
  - conda-forge::brotli-python=1.0.9
  - conda-forge::bzip2=1.0.8
  - conda-forge::c-ares=1.34.6
  - conda-forge::ca-certificates=2026.5.20
  - conda-forge::cached-property=1.5.2
  - conda-forge::cached_property=1.5.2
  - conda-forge::cachetools=4.2.4
  - conda-forge::certifi=2024.8.30
  - conda-forge::cffi=1.15.1
  - conda-forge::chardet=4.0.0
  - conda-forge::charset-normalizer=3.4.0
  - conda-forge::click=8.1.3
  - conda-forge::colorama=0.4.6
  - conda-forge::cryptography=38.0.2
  - conda-forge::cycler=0.11.0
  - conda-forge::debugpy=1.6.3
  - conda-forge::decorator=5.1.1
  - conda-forge::defusedxml=0.7.1
  - conda-forge::dill=0.3.8
  - conda-forge::docstring-to-markdown=0.15
  - conda-forge::entrypoints=0.4
  - conda-forge::exceptiongroup=1.2.2
  - conda-forge::expat=2.7.3
  - conda-forge::fftw=3.3.10
  - conda-forge::flake8=5.0.4
  - conda-forge::font-ttf-dejavu-sans-mono=2.37
  - conda-forge::font-ttf-inconsolata=3.000
  - conda-forge::font-ttf-source-code-pro=2.038
  - conda-forge::font-ttf-ubuntu=0.83
  - conda-forge::fontconfig=2.14.2
  - conda-forge::fonts-conda-ecosystem=1
  - conda-forge::fonts-conda-forge=1
  - conda-forge::fonttools=4.38.0
  - conda-forge::fqdn=1.5.1
  - conda-forge::freetype=2.12.1
  - conda-forge::gast=0.2.2
  - conda-forge::gcc_impl_linux-64=15.2.0
  - conda-forge::gcc_linux-64=15.2.0
  - conda-forge::gettext=0.25.1
  - conda-forge::gettext-tools=0.25.1
  - conda-forge::ghostscript=10.06.0
  - conda-forge::giflib=5.2.2
  - conda-forge::glib=2.80.2
  - conda-forge::glib-tools=2.80.2
  - conda-forge::google-auth=1.35.0
  - conda-forge::google-auth-oauthlib=0.4.6
  - conda-forge::google-pasta=0.2.0
  - conda-forge::grpcio=1.46.3
  - conda-forge::gxx_impl_linux-64=15.2.0
  - conda-forge::gxx_linux-64=15.2.0
  - conda-forge::h5py=2.10.0
  - conda-forge::icu=58.2
  - conda-forge::idna=3.10
  - conda-forge::importlib-metadata=4.11.4
  - conda-forge::importlib_metadata=4.11.4
  - conda-forge::importlib_resources=6.0.0
  - conda-forge::ipykernel=6.16.2
  - conda-forge::ipython=7.33.0
  - conda-forge::ipython_genutils=0.2.0
  - conda-forge::isoduration=20.11.0
  - conda-forge::isort=5.11.5
  - conda-forge::jack=1.9.21
  - conda-forge::jedi=0.18.2
  - conda-forge::jinja2=3.1.4
  - conda-forge::jpeg=9e
  - conda-forge::json5=0.9.25
  - conda-forge::jsonpointer=2.0
  - conda-forge::jsonschema=4.17.3
  - conda-forge::jsonschema-with-format-nongpl=4.17.3
  - conda-forge::jupyter_client=7.4.9
  - conda-forge::jupyter_core=4.11.1
  - conda-forge::jupyter_events=0.6.3
  - conda-forge::jupyter_server=1.23.4
  - conda-forge::jupyter_server_fileid=0.9.2
  - conda-forge::jupyter_server_ydoc=0.8.0
  - conda-forge::jupyter_ydoc=0.2.4
  - conda-forge::jupyterlab_pygments=0.3.0
  - conda-forge::keras=2.3.1
  - conda-forge::keras-applications=1.0.8
  - conda-forge::keras-preprocessing=1.1.2
  - conda-forge::kernel-headers_linux-64=4.18.0
  - conda-forge::keyutils=1.6.3
  - conda-forge::kiwisolver=1.4.4
  - conda-forge::krb5=1.20.1
  - conda-forge::lame=3.100
  - conda-forge::lazy-object-proxy=1.7.1
  - conda-forge::lcms2=2.14
  - conda-forge::ld_impl_linux-64=2.45.1
  - conda-forge::lerc=4.0.0
  - conda-forge::libasprintf=0.25.1
  - conda-forge::libasprintf-devel=0.25.1
  - conda-forge::libblas=3.11.0
  - conda-forge::libbrotlicommon=1.2.0
  - conda-forge::libbrotlidec=1.2.0
  - conda-forge::libbrotlienc=1.2.0
  - conda-forge::libcap=2.66
  - conda-forge::libcblas=3.11.0
  - conda-forge::libclang=14.0.6
  - conda-forge::libclang13=14.0.6
  - conda-forge::libcups=2.3.3
  - conda-forge::libdb=6.2.32
  - conda-forge::libedit=3.1.20250104
  - conda-forge::libev=4.33
  - conda-forge::libevent=2.1.12
  - conda-forge::libexpat=2.7.3
  - conda-forge::libffi=3.4.6
  - conda-forge::libflac=1.4.3
  - conda-forge::libgcc=15.2.0
  - conda-forge::libgcc-devel_linux-64=15.2.0
  - conda-forge::libgcc-ng=15.2.0
  - conda-forge::libgettextpo=0.25.1
  - conda-forge::libgettextpo-devel=0.25.1
  - conda-forge::libgfortran=15.2.0
  - conda-forge::libgfortran-ng=15.2.0
  - conda-forge::libgfortran5=15.2.0
  - conda-forge::libglib=2.80.2
  - conda-forge::libgomp=15.2.0
  - conda-forge::libgpuarray=0.7.6
  - conda-forge::libiconv=1.18
  - conda-forge::liblapack=3.11.0
  - conda-forge::liblapacke=3.11.0
  - conda-forge::libllvm14=14.0.6
  - conda-forge::libltdl=2.4.3a
  - conda-forge::libnsl=2.0.1
  - conda-forge::libogg=1.3.5
  - conda-forge::libopenblas=0.3.30
  - conda-forge::libopenssl-static=3.6.3
  - conda-forge::libopus=1.6.1
  - conda-forge::libprotobuf=3.17.2
  - conda-forge::libsanitizer=15.2.0
  - conda-forge::libsndfile=1.1.0
  - conda-forge::libsodium=1.0.18
  - conda-forge::libsqlite=3.46.0
  - conda-forge::libstdcxx=15.2.0
  - conda-forge::libstdcxx-devel_linux-64=15.2.0
  - conda-forge::libstdcxx-ng=15.2.0
  - conda-forge::libtiff=4.4.0
  - conda-forge::libtool=2.5.4
  - conda-forge::libudev1=253
  - conda-forge::libuuid=2.41.3
  - conda-forge::libuv=1.51.0
  - conda-forge::libvorbis=1.3.7
  - conda-forge::libwebp-base=1.6.0
  - conda-forge::libxcb=1.17.0
  - conda-forge::libxcrypt=4.4.36
  - conda-forge::libxkbcommon=1.0.3
  - conda-forge::mako=1.3.5
  - conda-forge::markdown=3.6
  - conda-forge::markupsafe=2.1.1
  - conda-forge::matplotlib=3.5.3
  - conda-forge::matplotlib-base=3.5.3
  - conda-forge::matplotlib-inline=0.1.7
  - conda-forge::mccabe=0.7.0
  - conda-forge::mistune=3.0.2
  - conda-forge::mpg123=1.31.3
  - conda-forge::multidict=6.0.2
  - conda-forge::munkres=1.1.4
  - conda-forge::mysql=5.7.20
  - conda-forge::mysql-common=8.3.0
  - conda-forge::mysql-libs=8.3.0
  - conda-forge::nbclassic=1.1.0
  - conda-forge::nbclient=0.7.0
  - conda-forge::nbconvert-core=7.6.0
  - conda-forge::nbformat=5.8.0
  - conda-forge::ncurses=6.5
  - conda-forge::nest-asyncio=1.6.0
  - conda-forge::nodejs=12.4.0
  - conda-forge::notebook=6.5.7
  - conda-forge::notebook-shim=0.2.4
  - conda-forge::nspr=4.38
  - conda-forge::nss=3.100
  - conda-forge::numpy=1.21.6
  - conda-forge::oauthlib=3.2.2
  - conda-forge::olefile=0.47
  - conda-forge::openblas=0.3.30
  - conda-forge::openjpeg=2.5.0
  - conda-forge::openssl=3.6.3
  - conda-forge::opt_einsum=3.3.0
  - conda-forge::packaging=23.2
  - conda-forge::pandocfilters=1.5.0
  - conda-forge::parso=0.8.4
  - conda-forge::pcre2=10.43
  - conda-forge::perl=5.32.1
  - conda-forge::perl-app-cpanminus=1.7048
  - conda-forge::perl-b-cow=0.007
  - conda-forge::perl-base=2.23
  - conda-forge::perl-business-isbn=3.007
  - conda-forge::perl-business-isbn-data=20210112.006
  - conda-forge::perl-carp=1.50
  - conda-forge::perl-clone=0.46
  - conda-forge::perl-common-sense=3.75
  - conda-forge::perl-compress-raw-bzip2=2.214
  - conda-forge::perl-compress-raw-zlib=2.214
  - conda-forge::perl-constant=1.33
  - conda-forge::perl-dbi=1.647
  - conda-forge::perl-digest-md5=2.59
  - conda-forge::perl-encode=3.21
  - conda-forge::perl-exporter=5.74
  - conda-forge::perl-extutils-makemaker=7.70
  - conda-forge::perl-file-path=2.18
  - conda-forge::perl-file-temp=0.2304
  - conda-forge::perl-file-which=1.24
  - conda-forge::perl-inc-latest=0.500
  - conda-forge::perl-log-log4perl=1.56
  - conda-forge::perl-mime-base64=3.16
  - conda-forge::perl-module-build=0.4234
  - conda-forge::perl-parent=0.243
  - conda-forge::perl-pathtools=3.75
  - conda-forge::perl-scalar-list-utils=1.70
  - conda-forge::perl-storable=3.15
  - conda-forge::perl-test-fatal=0.016
  - conda-forge::perl-test-needs=0.002009
  - conda-forge::perl-test-nowarnings=1.06
  - conda-forge::perl-test-warnings=0.031
  - conda-forge::perl-try-tiny=0.31
  - conda-forge::perl-unix-processors=2.046
  - conda-forge::perl-uri=5.17
  - conda-forge::perl-xml-namespacesupport=1.12
  - conda-forge::perl-xml-parser=2.44_01
  - conda-forge::perl-xml-sax=1.02
  - conda-forge::perl-xml-sax-base=1.09
  - conda-forge::perl-xml-sax-expat=0.51
  - conda-forge::pexpect=4.9.0
  - conda-forge::pickleshare=0.7.5
  - conda-forge::pip=24.0
  - conda-forge::pkgutil-resolve-name=1.3.10
  - conda-forge::platformdirs=4.0.0
  - conda-forge::pluggy=1.0.0
  - conda-forge::ply=3.11
  - conda-forge::prometheus_client=0.17.1
  - conda-forge::prompt-toolkit=3.0.48
  - conda-forge::protobuf=3.17.2
  - conda-forge::psutil=5.9.3
  - conda-forge::pthread-stubs=0.4
  - conda-forge::ptyprocess=0.7.0
  - conda-forge::pulseaudio=14.0
  - conda-forge::pyasn1=0.5.1
  - conda-forge::pyasn1-modules=0.3.0
  - conda-forge::pycodestyle=2.9.1
  - conda-forge::pycparser=2.21
  - conda-forge::pyflakes=2.5.0
  - conda-forge::pygments=2.17.2
  - conda-forge::pygpu=0.7.6
  - conda-forge::pyjwt=2.8.0
  - conda-forge::pylint=2.16.4
  - conda-forge::pyopenssl=23.2.0
  - conda-forge::pyparsing=3.1.4
  - conda-forge::pyqt=5.15.4
  - conda-forge::pyqt5-sip=12.9.0
  - conda-forge::pyrsistent=0.18.1
  - conda-forge::pysocks=1.7.1
  - conda-forge::python=3.7.12
  - conda-forge::python-dateutil=2.9.0
  - conda-forge::python-fastjsonschema=2.20.0
  - conda-forge::python-flatbuffers=1.12
  - conda-forge::python-json-logger=2.0.7
  - conda-forge::python-lsp-jsonrpc=1.0.0
  - conda-forge::python-lsp-server=1.7.4
  - conda-forge::python-lsp-server-base=1.7.4
  - conda-forge::python_abi=3.7
  - conda-forge::pytoolconfig=1.2.5
  - conda-forge::pytz=2024.2
  - conda-forge::pyu2f=0.1.5
  - conda-forge::pyyaml=6.0
  - conda-forge::pyzmq=24.0.1
  - conda-forge::re2=2021.04.01
  - conda-forge::readline=8.3
  - conda-forge::requests=2.32.2
  - conda-forge::requests-oauthlib=2.0.0
  - conda-forge::rfc3339-validator=0.1.4
  - conda-forge::rfc3986-validator=0.1.1
  - conda-forge::rope=1.11.0
  - conda-forge::rsa=4.9
  - conda-forge::scikit-learn=0.20.3
  - conda-forge::send2trash=1.8.3
  - conda-forge::setuptools=69.0.3
  - conda-forge::sip=6.5.1
  - conda-forge::six=1.16.0
  - conda-forge::snappy=1.1.10
  - conda-forge::sniffio=1.3.1
  - conda-forge::snowballstemmer=2.2.0
  - conda-forge::soupsieve=2.3.2.post1
  - conda-forge::sqlite=3.46.0
  - conda-forge::sysroot_linux-64=2.28
  - conda-forge::tabulate=0.9.0
  - conda-forge::tensorboard=1.15.0
  - conda-forge::tensorboard-plugin-wit=1.8.1
  - conda-forge::termcolor=1.1.0
  - conda-forge::terminado=0.17.1
  - conda-forge::theano=1.0.4
  - conda-forge::tinycss2=1.4.0
  - conda-forge::tk=8.6.13
  - conda-forge::toml=0.10.2
  - conda-forge::tomli=2.0.2
  - conda-forge::tomlkit=0.12.5
  - conda-forge::tornado=6.2
  - conda-forge::tqdm=4.67.1
  - conda-forge::traitlets=5.9.0
  - conda-forge::typed-ast=1.5.4
  - conda-forge::typing-extensions=4.7.1
  - conda-forge::typing_extensions=4.7.1
  - conda-forge::tzdata=2025c
  - conda-forge::ujson=5.5.0
  - conda-forge::unicodedata2=14.0.0
  - conda-forge::uri-template=1.3.0
  - conda-forge::urllib3=2.2.1
  - conda-forge::wcwidth=0.2.10
  - conda-forge::webcolors=1.13
  - conda-forge::webencodings=0.5.1
  - conda-forge::websocket-client=1.6.1
  - conda-forge::werkzeug=0.16.1
  - conda-forge::whatthepatch=1.0.6
  - conda-forge::wheel=0.42.0
  - conda-forge::wrapt=1.14.1
  - conda-forge::xcb-util=0.4.1
  - conda-forge::xcb-util-image=0.4.0
  - conda-forge::xcb-util-keysyms=0.4.0
  - conda-forge::xcb-util-renderutil=0.3.10
  - conda-forge::xcb-util-wm=0.4.1
  - conda-forge::xorg-libx11=1.8.13
  - conda-forge::xorg-libxau=1.0.12
  - conda-forge::xorg-libxdmcp=1.1.5
  - conda-forge::y-py=0.5.4
  - conda-forge::yaml=0.2.5
  - conda-forge::yapf=0.33.0
  - conda-forge::yarl=1.7.2
  - conda-forge::ypy-websocket=0.8.2
  - conda-forge::zeromq=4.3.5
  - conda-forge::zipp=3.15.0
  # --- bioconda ---
  - bioconda::deeplift=0.6.13.0
  - bioconda::meme=4.11.2
  - bioconda::perl-cgi=4.71
  - bioconda::perl-config-general=2.67
  - bioconda::perl-encode-locale=1.05
  - bioconda::perl-file-spec=3.48_01
  - bioconda::perl-html-parser=3.83
  - bioconda::perl-html-tagset=3.24
  - bioconda::perl-html-template=2.97
  - bioconda::perl-html-tree=5.07
  - bioconda::perl-http-date=6.06
  - bioconda::perl-http-message=7.01
  - bioconda::perl-io-html=1.004
  - bioconda::perl-json=4.10
  - bioconda::perl-json-xs=4.04
  - bioconda::perl-lwp-mediatypes=6.04
  - bioconda::perl-math-cdf=0.1
  - bioconda::perl-sys-info=0.7811
  - bioconda::perl-sys-info-base=0.7807
  - bioconda::perl-sys-info-driver-linux=0.7911
  - bioconda::perl-text-template-simple=0.91
  - bioconda::perl-time-local=1.35
  - bioconda::perl-timedate=2.33
  - bioconda::perl-types-serialiser=1.01
  - bioconda::perl-url-encode=0.03
  - bioconda::perl-xml-simple=2.25
  - bioconda::perl-yaml=1.30
  - bioconda::pybigwig=0.3.22
  - bioconda::pyfaidx=0.9.0.3
  - bioconda::pysam=0.16.0
  - bioconda::pyvcf3=1.0.3
  # --- UCSC tools (bioconda) ---
  - bioconda::ucsc-bigbedinfo=469
  - bioconda::ucsc-bigbedtobed=469
  - bioconda::ucsc-bigwigaverageoverbed=469
  - bioconda::ucsc-bigwiginfo=469
  - bioconda::ucsc-bigwigsummary=469
  - bioconda::ucsc-bigwigtobedgraph=469
  - bioconda::ucsc-bigwigtowig=469
  - bioconda::ucsc-fasize=469
  - bioconda::ucsc-fasplit=469
  - bioconda::ucsc-fatotwobit=472
  - bioconda::ucsc-wigtobigwig=472
  # --- pip ---
  - pip:
    - modisco==0.5.1.1
    - psrecord==1.4