#!/bin/sh
#SBATCH --partition=epyc
#SBATCH --time=3-00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=6G
#SBATCH --job-name=Train_mLS-GKM
#SBATCH --error=%x-%A_%a.out
#SBATCH --output=%x-%A_%a.out
#SBATCH --array=1-333%75

config_file=bigbed_list.tsv
EXP_NAME=$(awk -v SLURM_ARRAY_TASK_ID=$SLURM_ARRAY_TASK_ID '$1==SLURM_ARRAY_TASK_ID {print $3}' $config_file)

mkdir -p Models/mLS-GKM_Models


# All params other than kernel and cache memory size are default, just written here to be explicit
/mnt/scratch45/c24080990/lsgkm_multi_explain_KH/bin/gkmtrain \
    -t 3 \
    -l 11 \
    -k 7 \
    -d 3 \
    -c 10 \
    -g 2 \
    -c 1 \
    -e 0.001 \
    -w 1 \
    -m 4000 \
    -T 4 \
    FASTAs/$EXP_NAME/train_positive.fa \
    FASTAs/$EXP_NAME/train_negative.fa \
    Models/mLS-GKM_Models/$EXP_NAME
